#QUESTION 10
f = open("answers.txt", "w")
f.write("ANSWERS TO WEEK 8 QUIZ\n")
f.write("QUESTION 1: C\n")
f.write("QUESTION 2: A\n")
f.write("QUESTION 3: B\n")
f.write("QUESTION 4: B\n")
f.write("QUESTION 5: D\n")
f.write("QUESTION 6: C\n")
f.write("QUESTION 7: D\n")
f.write("QUESTION 8: A\n")
f.write("QUESTION 9: A\n")
f.write("QUESTION 10: A\n")
f.write("QUESTION 11: D\n")
f.write("QUESTION 12: B\n")
f.write("QUESTION 13: A\n")
f.write("QUESTION 14: C\n")
f.write("QUESTION 15: C\n")
f.write("QUESTION 16: A\n")
f.write("QUESTION 17: D\n")
f.write("QUESTION 18: C\n")
f.write("QUESTION 19: D\n")
f.write("QUESTION 20: A\n")
f.write("QUESTION 21: B\n")
f.write("QUESTION 22: D\n")
f.write("QUESTION 23: B\n")
f.write("QUESTION 24: A\n")
f.write("QUESTION 25: B\n")
f.write("QUESTION 26: B\n")
f.write("QUESTION 27: A\n")
f.write("QUESTION 28: A\n")
f.write("QUESTION 29: A\n")
f.write("QUESTION 30: B\n")
f.write("QUESTION 31: D\n")
f.write("QUESTION 32: C\n")
f.write("QUESTION 33: C\n")
f.write("QUESTION 34: B\n")
f.write("QUESTION 35: A\n")
f.write("QUESTION 36: B\n")
f.write("QUESTION 37: B\n")
f.write("QUESTION 38: D\n")
f.write("QUESTION 39: B\n")
f.write("QUESTION 40: A\n")
f.close()

#open and read the file after the appending:
f = open("answers.txt", "r")
print(f.read())